### ISSUE TITLE
Formula.Firewall: Query Errors. 

### ISSUE THREAD

**Issue by ryanperrymba** [didierterrien/Power-BI-assistant#3]
Hi Didier,

This looks like an absolutely awesome tool.  I've attempted to use it. After editing my WindowsUserName parameter, per the intro page instructions, upon data refresh, I get the infamous <Query Name> references other queries or steps, so it may not directly access a data source." error on multiple tables.  I've tried refreshing tables one at a time. Is this a known issue with a workaround? 

This occurs on the followingtables:
PBI Reports ID
Source Files
Members
Memory Consumption
Columns & Measures
Formulas cross reference

Also, the "Memory" query errors: "The name 'Query_' wasn't recognized. Make sure it's spelled correctly.

Troubleshooting: When attempting to refresh all, the first query that fails is the PBI Reports ID, which states "We cannot convert he value false to type Table.  Looking at the query, it appears this occurs immediately upon the Ports = MSMDSRVports() line. 

I noted that I had put in my windows username with the @mydomain.com domain included and noted the FolderFiles query was returning False. Looking at the query, I could see it was looking for files in my user.name folder and updated the parameter to omit the domain. This allowed the FolderFiles query to load, but the other errors still persist.

**Comment by didierterrien** [comment]
Hello Ryan,
Thank you for your interrest in Power BI assistant.
I could notice only few issues about the windows user name that you solved already. I'm currently writing a blog with more details & screenshots about Power BI assistant.
The windows user name must be exactly the name of the folder you can find in C:\users\
Please check carefully
After you typed the parameter, please refresh Power BI assistant report.
If it still doesn't work, please send me screenshots of the errors you get after you solved the username issue.
I will try my best to help.
Have a good day
Didier

**Comment by didierterrien** [comment]
Hello Ryan,
I added V2-3 of the pbix file with some improvements
Please check my blog post here for more debugging options: 
[http://didier.terrien.free.fr/powerbi/index.php/category/power-bi-assistant-troubleshooting/](http://didier.terrien.free.fr/powerbi/index.php/category/power-bi-assistant-troubleshooting)
Let me know if you still get problems 
Didier

**Comment by didierterrien** [comment]
Hello Ryan,

Thank you very much for helping me to debug the queries. It’s quite difficult from here 😊  So I updated the blog post and, first, suggested to open only 'Power BI assistant' report and make it work with itself.

I could get the same error than you while I used Power BI desktop downloaded from Windows store (I use more the version downloaded on the web site). The only workaround I could find was to change your options settings. I added some screenshots in the blog :
[https://thebipower.fr/index.php/2019/02/18/power-bi-assistant-troubleshouting/](https://thebipower.fr/index.php/2019/02/18/power-bi-assistant-troubleshouting/)

Hope it will solve the problem. Please let me know

Didier
