### ISSUE TITLE
Power-BI-assistant not working for reports developed on Azure Analysis Service(Cube)

### ISSUE THREAD

**Issue by kgopi007** [didierterrien/Power-BI-assistant#4]
Hi Didier Terrien,

I have downloaded your Power BI assistant V2-3.pbix and used it to compare two power bi reports which are developed on SQL DB Tables as Datasource. I was amazed by its work and it is really helpful.
But most my of reports are developed with Azure Analysis Service as a datasource(which doesn't have tables/relationships/model inside PBIX).

Power BI assistant V2-3.pbix  is not able to recognize these reports.
I know this is not an issue with existing features of Power BI assistant V2-3.pbix but still adding to know if I am missing something.

regards,
GOPI K

**Comment by didierterrien** [comment]
Hello,
Sorry for the delay but I was in vacations. Thanks for your interrest in Power BI assistant.
You are totally right; Power BI assistant wasn't tested with SSAS datasources. I may be able to do it in the future but I cannot plan it for the moment.
Did you try other documentation ways ? (https://thebipower.fr/index.php/model-documentation/)
Or once your report is published to the service you may try Chris Webb trick : https://www.youtube.com/watch?v=fseh56DYeLc
Any way, if you find a way to solve the problem, I would be glad to know how so I can share it on my web site.
Regards
Didier
